mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guo.domain

# 默认是8080端口 , 配置为80端口在浏览器访问时不需要输入端口号
server:
  port: 80

spring:
  # 用户名 密码 需要根据实际情况修改
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: adminadmin
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: admin
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  resources:
    chain:
      cache: true
logging:
  level:
    # 为了避免信息过载，根日志级别保持INFO
    root: INFO
    # 将Spring Boot的日志级别设为DEBUG，以获取详细的条件报告
    org.springframework.boot: DEBUG
    # 将你自己项目的日志级别也设为DEBUG
    com.guo: DEBUG